variables:
  # Định nghĩa phiên bản của Docker image sử dụng GitLab CI/CD
  DOCKER_IMAGE_FE: ${REGISTRY_URL}/${REGISTRY_PROJECT}/frontend:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
  DOCKER_IMAGE_BE: ${REGISTRY_URL}/${REGISTRY_PROJECT}/backend:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
  DOCKER_IMAGE_ADMIN: ${REGISTRY_URL}/${REGISTRY_PROJECT}/admin:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
  DOCKER_CONTAINER_FE: frontend-container
  DOCKER_CONTAINER_BE: backend-container
  DOCKER_CONTAINER_ADMIN: admin-container

stages:
  - install
  - buildandpush
  - deploy

# Giai đoạn cài đặt dependencies
install:
  stage: install
  image: node:18  # Sử dụng Node.js phù hợp với dự án
  cache:
    key: ${CI_COMMIT_REF_SLUG}  # Cache theo nhánh
    paths:
      - node_modules/
  script:
    - npm install
  tags:
    - dev-server-apple-store

# Giai đoạn build và push Docker image
buildandpush:
  stage: buildandpush
  image: docker:latest  # Sử dụng image Docker chính thức
  services:
    - docker:dind  # Docker in Docker để build và push image
  before_script:
    - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - docker build -t $DOCKER_IMAGE_FE ./frontend  # Build Docker image cho frontend
    - docker build -t $DOCKER_IMAGE_BE ./backend  # Build Docker image cho backend
    - docker build -t $DOCKER_IMAGE_ADMIN ./admin  # Build Docker image cho admin
    - docker push $DOCKER_IMAGE_FE  # Push Docker image frontend
    - docker push $DOCKER_IMAGE_BE  # Push Docker image backend
    - docker push $DOCKER_IMAGE_ADMIN  # Push Docker image admin
  tags:
    - dev-server-apple-store

# Giai đoạn deploy
deploy:
  stage: deploy
  image: node:18  # Sử dụng Node.js để chạy ứng dụng
  before_script:
    - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    # Tạo file .env cho frontend từ ENV_FRONTEND
    - echo "$ENV_FRONTEND" > ./frontend/.env
    # Tạo file .env cho backend từ ENV_BACKEND
    - echo "$ENV_BACKEND" > ./backend/.env
    # Tạo file .env cho admin từ ENV_ADMIN
    - echo "$ENV_ADMIN" > ./admin/.env

    # Kiểm tra nội dung các file .env (chỉ để kiểm tra, có thể xóa khi deploy thật)
    - echo "Frontend .env:"
    - cat ./frontend/.env
    - echo "Backend .env:"
    - cat ./backend/.env
    - echo "Admin .env:"
    - cat ./admin/.env

    # Kéo image từ registry về server và chạy các container cho từng project
    - docker pull $DOCKER_IMAGE_FE
    - docker pull $DOCKER_IMAGE_BE
    - docker pull $DOCKER_IMAGE_ADMIN

    # Xoá container cũ nếu có
    - docker rm -f $DOCKER_CONTAINER_FE || true
    - docker rm -f $DOCKER_CONTAINER_BE || true
    - docker rm -f $DOCKER_CONTAINER_ADMIN || true

    # Chạy các container mới với port riêng biệt
    - docker run --name $DOCKER_CONTAINER_FE -dp 4000:4000 $DOCKER_IMAGE_FE
    - docker run --name $DOCKER_CONTAINER_BE -dp 5001:5001 $DOCKER_IMAGE_BE
    - docker run --name $DOCKER_CONTAINER_ADMIN -dp 4001:4001 $DOCKER_IMAGE_ADMIN

  tags:
    - dev-server-apple-store
