variables:
  DOCKER_IMAGE_FE: "${REGISTRY_URL}/${REGISTRY_PROJECT}/frontend:${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME}}_${CI_COMMIT_SHORT_SHA}"
  DOCKER_IMAGE_BE: "${REGISTRY_URL}/${REGISTRY_PROJECT}/backend:${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME}}_${CI_COMMIT_SHORT_SHA}"
  DOCKER_IMAGE_ADMIN: "${REGISTRY_URL}/${REGISTRY_PROJECT}/admin:${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME}}_${CI_COMMIT_SHORT_SHA}"
  DOCKER_CONTAINER_FE: "${CI_PROJECT_NAME}-frontend"
  DOCKER_CONTAINER_BE: "${CI_PROJECT_NAME}-backend"
  DOCKER_CONTAINER_ADMIN: "${CI_PROJECT_NAME}-admin"  

stages:
  - build
  - deploy

build_images:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - cat "$FE_ENV_FILE" > ./frontend/.env
    - cat "$BE_ENV_FILE" > ./backend/.env
    - cat "$ADMIN_ENV_FILE" > ./admin/.env

    - echo "Logging into Docker registry..."
    - export DOCKER_BUILDKIT=1 
    - docker login $REGISTRY_URL -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t ${DOCKER_IMAGE_FE} ./frontend || echo "Error during frontend build"
    - docker push $DOCKER_IMAGE_FE || echo "Error during frontend push"
    - docker build -t ${DOCKER_IMAGE_BE} ./backend || echo "Error during backend build"
    - docker push $DOCKER_IMAGE_BE || echo "Error during backend push"
    - docker build -t ${DOCKER_IMAGE_ADMIN} ./admin || echo "Error during admin build"
    - docker push $DOCKER_IMAGE_ADMIN || echo "Error during admin push"
    - echo "=== Docker Build and Push Completed ==="
  tags:
    - cloud-gitlab-apple
  only:
    - main

deploy: 
  stage: deploy
  image: node:18
  before_script:
    - echo "Logging into Docker registry..."
    - docker login $REGISTRY_URL -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - echo "Pulling Deploy Docker images..."
    - docker pull $DOCKER_IMAGE_FE
    - docker pull $DOCKER_IMAGE_BE
    - docker pull $DOCKER_IMAGE_ADMIN

    - echo "Removing existing containers..."
    - docker rm -f $DOCKER_CONTAINER_FE || true
    - docker rm -f $DOCKER_CONTAINER_BE || true
    - docker rm -f $DOCKER_CONTAINER_ADMIN || true
    - echo "run  containers..."
    - docker run --name $DOCKER_CONTAINER_FE -dp 4000:4000 $DOCKER_IMAGE_FE
    - docker run --name $DOCKER_CONTAINER_BE -dp 5001:5001 $DOCKER_IMAGE_BE
    - docker run --name $DOCKER_CONTAINER_ADMIN -dp 4001:4001 $DOCKER_IMAGE_ADMIN
  tags:
    - cloud-gitlab-apple    
  only:
    - main



