stages:
  - build
  - push

# Biến môi trường chung
variables:
  DOCKER_IMAGE_FE: ${REGISTRY_URL}/${REGISTRY_PROJECT}/frontend:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
  DOCKER_IMAGE_BE: ${REGISTRY_URL}/${REGISTRY_PROJECT}/backend:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
  DOCKER_IMAGE_ADMIN: ${REGISTRY_URL}/${REGISTRY_PROJECT}/admin:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}

# Job build Docker images
build_images:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - echo "Building Docker images..."
    - docker build -t $DOCKER_IMAGE_FE ./frontend  # Build Docker image cho frontend
    - docker push $DOCKER_IMAGE_FE  # Push Docker image cho frontend
    - docker build -t $DOCKER_IMAGE_BE ./backend
    - docker push $DOCKER_IMAGE_BE   # Build Docker image cho backend
    - docker build -t $DOCKER_IMAGE_ADMIN ./admin
    - docker push $DOCKER_IMAGE_ADMIN  # Build Docker image cho admin
  tags:
    - dev-server-apple-store

