version: '3'
services:
  backend:
    build:
      context: ./health-backend
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8  # Google DNS
      - 1.1.1.1
    ports:
      - "3001:3000"  # Backend chạy trên port 3000 bên trong container, map ra port 3001 trên host
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
      image: mongo:latest
      container_name: mongo
      ports:
        - "27017:27017" # MongoDB port
      volumes:
        - mongo-data:/data/db

volumes:
  mongo-data:
