version: '3.8'

services:
  frontend:
    image: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
    container_name: frontend-container
    ports:
      - "4000:4000"
    environment:
      NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_API_URL
    volumes:
      - ./frontend:/app
    networks:
      - macstore-net
    depends_on:
      - backend

  backend:
    image: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA
    container_name: backend-container
    ports:
      - "5001:5001"
    environment:
      MONGODB_URI: $MONGODB_URI
      JWT_SECRET: $JWT_SECRET
      ACCESS_TOKEN: $ACCESS_TOKEN
      REFRESH_TOKEN: $REFRESH_TOKEN
      CORS_ORIGIN: $CORS_ORIGIN
    volumes:
      - ./backend:/app
    networks:
      - macstore-net
    depends_on:
      - redis

  admin:
    image: $CI_REGISTRY_IMAGE/admin:$CI_COMMIT_SHORT_SHA
    container_name: admin-container
    ports:
      - "4001:4001"
    environment:
      NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_API_URL
    volumes:
      - ./admin:/app
    networks:
      - macstore-net
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - macstore-net

networks:
  macstore-net:
    driver: bridge
